//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CryptoWebService {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CryptoWebService.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Działanie.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angielski.
        /// </summary>
        public static string Alphabet_EN {
            get {
                return ResourceManager.GetString("Alphabet_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angielski z cyframi.
        /// </summary>
        public static string Alphabet_EN_Digit {
            get {
                return ResourceManager.GetString("Alphabet_EN_Digit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angielski rozszerzony.
        /// </summary>
        public static string Alphabet_EN_Extended {
            get {
                return ResourceManager.GetString("Alphabet_EN_Extended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polski.
        /// </summary>
        public static string Alphabet_PL {
            get {
                return ResourceManager.GetString("Alphabet_PL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polski z cyframi.
        /// </summary>
        public static string Alphabet_PL_Digit {
            get {
                return ResourceManager.GetString("Alphabet_PL_Digit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polski rozszerzony.
        /// </summary>
        public static string Alphabet_PL_Extended {
            get {
                return ResourceManager.GetString("Alphabet_PL_Extended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dostępne znaki.
        /// </summary>
        public static string AvailableCharacters {
            get {
                return ResourceManager.GetString("AvailableCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz alfabet.
        /// </summary>
        public static string ChooseAlphabet {
            get {
                return ResourceManager.GetString("ChooseAlphabet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odszyfrowany tekst.
        /// </summary>
        public static string DecryptedText {
            get {
                return ResourceManager.GetString("DecryptedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deszyfrator.
        /// </summary>
        public static string Decryptor {
            get {
                return ResourceManager.GetString("Decryptor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opis.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaszyfrowany tekst.
        /// </summary>
        public static string EncryptedText {
            get {
                return ResourceManager.GetString("EncryptedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szyfrator.
        /// </summary>
        public static string Encryptor {
            get {
                return ResourceManager.GetString("Encryptor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wpisano niedozwolony znak!.
        /// </summary>
        public static string InvalidCharacter {
            get {
                return ResourceManager.GetString("InvalidCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klucz.
        /// </summary>
        public static string Key {
            get {
                return ResourceManager.GetString("Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wpisz tekst do odszyfrowania.
        /// </summary>
        public static string WriteTextToDecrypt {
            get {
                return ResourceManager.GetString("WriteTextToDecrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wpisz tekst do zaszyfrowania.
        /// </summary>
        public static string WriteTextToEncrypt {
            get {
                return ResourceManager.GetString("WriteTextToEncrypt", resourceCulture);
            }
        }
    }
}
