//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CryptoWebService {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CryptoWebService.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Działanie.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wartość A.
        /// </summary>
        public static string AffineCipherKeyA {
            get {
                return ResourceManager.GetString("AffineCipherKeyA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wartość B.
        /// </summary>
        public static string AffineCipherKeyB {
            get {
                return ResourceManager.GetString("AffineCipherKeyB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algorytm.
        /// </summary>
        public static string Algorithm {
            get {
                return ResourceManager.GetString("Algorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angielski.
        /// </summary>
        public static string Alphabet_EN {
            get {
                return ResourceManager.GetString("Alphabet_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angielski z cyframi.
        /// </summary>
        public static string Alphabet_EN_Digit {
            get {
                return ResourceManager.GetString("Alphabet_EN_Digit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angielski rozszerzony.
        /// </summary>
        public static string Alphabet_EN_Extended {
            get {
                return ResourceManager.GetString("Alphabet_EN_Extended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polski.
        /// </summary>
        public static string Alphabet_PL {
            get {
                return ResourceManager.GetString("Alphabet_PL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polski z cyframi.
        /// </summary>
        public static string Alphabet_PL_Digit {
            get {
                return ResourceManager.GetString("Alphabet_PL_Digit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polski rozszerzony.
        /// </summary>
        public static string Alphabet_PL_Extended {
            get {
                return ResourceManager.GetString("Alphabet_PL_Extended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dostępne znaki.
        /// </summary>
        public static string AvailableCharacters {
            get {
                return ResourceManager.GetString("AvailableCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szyfry blokowe.
        /// </summary>
        public static string BlockCiphers {
            get {
                return ResourceManager.GetString("BlockCiphers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kalkulator.
        /// </summary>
        public static string Calculator {
            get {
                return ResourceManager.GetString("Calculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz alfabet.
        /// </summary>
        public static string ChooseAlphabet {
            get {
                return ResourceManager.GetString("ChooseAlphabet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deszyfruj.
        /// </summary>
        public static string Decrypt {
            get {
                return ResourceManager.GetString("Decrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odszyfrowany tekst.
        /// </summary>
        public static string DecryptedText {
            get {
                return ResourceManager.GetString("DecryptedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deszyfrator.
        /// </summary>
        public static string Decryptor {
            get {
                return ResourceManager.GetString("Decryptor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opis.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szyfruj.
        /// </summary>
        public static string Encrypt {
            get {
                return ResourceManager.GetString("Encrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaszyfrowany tekst.
        /// </summary>
        public static string EncryptedText {
            get {
                return ResourceManager.GetString("EncryptedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tryb szyfrowania.
        /// </summary>
        public static string EncryptMode {
            get {
                return ResourceManager.GetString("EncryptMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szyfrator.
        /// </summary>
        public static string Encryptor {
            get {
                return ResourceManager.GetString("Encryptor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szyfrowanie pliku.
        /// </summary>
        public static string FileEncryption {
            get {
                return ResourceManager.GetString("FileEncryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skrót.
        /// </summary>
        public static string Hash {
            get {
                return ResourceManager.GetString("Hash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wysokość.
        /// </summary>
        public static string HeightMode {
            get {
                return ResourceManager.GetString("HeightMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wpisano niedozwolony znak!.
        /// </summary>
        public static string InvalidCharacter {
            get {
                return ResourceManager.GetString("InvalidCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klucz.
        /// </summary>
        public static string Key {
            get {
                return ResourceManager.GetString("Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Długość klucza.
        /// </summary>
        public static string KeyLength {
            get {
                return ResourceManager.GetString("KeyLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funkcja skrótu MD5.
        /// </summary>
        public static string MD5Hash {
            get {
                return ResourceManager.GetString("MD5Hash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funkcja skrótu SHA-1.
        /// </summary>
        public static string SHA1Hash {
            get {
                return ResourceManager.GetString("SHA1Hash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funkcja skrótu SHA-256.
        /// </summary>
        public static string SHA256Hash {
            get {
                return ResourceManager.GetString("SHA256Hash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funkcja skrótu SHA-512.
        /// </summary>
        public static string SHA512Hash {
            get {
                return ResourceManager.GetString("SHA512Hash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szyfrowanie tekstu.
        /// </summary>
        public static string TextEncryption {
            get {
                return ResourceManager.GetString("TextEncryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szerokość.
        /// </summary>
        public static string WidthMode {
            get {
                return ResourceManager.GetString("WidthMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wpisz tekst do odszyfrowania.
        /// </summary>
        public static string WriteTextToDecrypt {
            get {
                return ResourceManager.GetString("WriteTextToDecrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wpisz tekst do zaszyfrowania.
        /// </summary>
        public static string WriteTextToEncrypt {
            get {
                return ResourceManager.GetString("WriteTextToEncrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wpisz tekst do obliczenia skrótu.
        /// </summary>
        public static string WriteTextToHash {
            get {
                return ResourceManager.GetString("WriteTextToHash", resourceCulture);
            }
        }
    }
}
